os:
  - linux

addons:
  apt:
    packages:
      - gcc-multilib
      - cmake

before_script:
  - git clone https://github.com/Zeex/pawn.git
  - cd pawn
  - cmake source/compiler -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - make
  - cd ..
  
script:
  - LD_LIBRARY_PATH=pawn/ pawn/pawncc gamemodes/wsserver.pwn -ogamemodes/wsserver.amx -ipawno/include
  - LD_LIBRARY_PATH=pawn/ pawn/pawncc gamemodes/wsclient.pwn -ogamemodes/wsclient.amx -ipawno/include
