os:
  - linux

language: c

addons:
  apt:
    packages:
      - gcc-multilib
      - cmake
      - lib32stdc++6

before_script:
  - git clone https://github.com/Zeex/pawn.git
  - cd pawn
  - cmake source/compiler -DCMAKE_BUILD_TYPE=RelWithDebInfo
                          -DCMAKE_C_FLAGS=-m32
  - make
  - cd ..
  
script:
  - LD_LIBRARY_PATH=pawn/ pawn/pawncc gamemodes/test.pwn -ogamemodes/test.amx -ipawno/include
  - chmod u+x samp03svr
  - ./samp03svr

